### ISSUE TITLE
Do people normally install parcel on a per-project basis?

### ISSUE THREAD

**Issue by chiroptical** [taezos/umu-halogen#6]
https://github.com/taezos/umu-halogen/blob/eb0dc97aa532b4d7ecb83195136a59b56333ed7b/templates/Makefile#L20

It isn't obvious to me but I would have installed `parcel` globally instead of locally. What do you think?

**Comment by piq9117** [comment]
From their docs, it looks like they're suggesting to install `parcel` globally but I'm thinking this will generate a "deployable" project. Where we can hopefully just throw this project in a server and work without searching for a bunch of dependencies.
